# Generated by Django 4.0.4 on 2022-05-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='given_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
